### ISSUE TITLE
Chain validation failed when trying to download binaries

### ISSUE THREAD

**Issue by mueller-ma** [dkanada/Syncopoli#2]
LineageOS 14.1
Android 7.1.2

Your lets encryt cert expired. Why dont you just upload the binaries on github and download them from here?

**Comment by dkanada** [comment]
This actually isn't my project, I cloned the repo from gitlab which is where the main developer is hosting it. I was also wondering why the binaries aren't just downloaded from the git repository. Maybe github or gitlab have a policy against excessive downloading of files or something.

**Comment by mueller-ma** [comment]
https://gitlab.com/fengshaun/syncopoli/issues/44

**Comment by mueller-ma** [comment]
Maybe you should link to the repo in gitlab
